### ISSUE TITLE
Not getting any output on the screen

### ISSUE THREAD

**Issue by htilly** [bureus/MMM-SHL#1] opened 2019-09-13 13:02 UTC
First of, thanks!!
Just the module Ive been looking for..

However I can't get any output from the module.
I got the API and according to the log I get data back. But nothing is displayed.. 
Tried both with filter on teamID and without.

See below for config and logs. Please advice.

Config:
    {
            module: "MMM-SHL",
            position: "middle.center",

            config: {
                clientId: "CLIENT_ID", 
                clientSecret: "CLIENT_SECRET"
              //  teams: ['FBK', 'FHC', 'DIF'] 
            }
     },

1|MagicMirror  | 2:55:38 PM MMM-SHL: Number of games: 364
1|MagicMirror  | 2:55:38 PM MMM-SHL: Getting standings
1|MagicMirror  | 2:55:39 PM MMM-SHL: Standings retrived: []
1|MagicMirror  | 2:55:39 PM MMM-SHL: Number of teams: 0
1|MagicMirror  | 2:55:39 PM MMM-SHL: []
1|MagicMirror  | 2:55:39 PM MMM-SHL: []
1|MagicMirror  | 2:55:39 PM MMM-SHL: Sceduled refresh at: Sat Sep 14 2019 18:00:00 GMT+0200 (CEST)
1|MagicMirror  | Use existing news fetcher for url: http://www.svd.se/?service=rss
1|MagicMirror  | 2:55:49 PM MMM-SHL: socketNotificationReceived
1|MagicMirror  | 2:55:49 PM MMM-SHL: CONFIG event received
1|MagicMirror  | 2:55:49 PM MMM-SHL: Getting standings
1|MagicMirror  | [2:55:49 PM] - MMM-Namnsdag : Fetching todays names
1|MagicMirror  | 2:55:50 PM MMM-SHL: Games retrived: [{"away_team_code":"FBK","away_team_result":0,"game_center_active":false,"game_id":10730,"game_type":"Regular season game","game_uuid":"qWX-3455RNQ0J","highlights_coverage_enabled":false,"home_team_code":"VLH","home_team_result":0,"live_coverage_enabled":false,"overtime":false,"penalty_shots":false,"played":false,"season":"2019","series":"SHL","start_date_time":"2020-03-12T19:00:00+0100","ticket_url":"http://vlh.ebiljett.nu/Home/tickets/422/False?style=shl","tv_channels":[],"venue":"Vida Arena"},{"away_team_code":"MIF","away_team_result":0,"game_center_ac
...
...
...
...
me/tickets/367/False?style=shl","tv_channels":[],"venue":"Tegera Arena"},{"away_team_code":"IKO","away_team_result":0,"game_center_active":true,"game_center_url_desktop":"http://shl.se/gamecenter/qWX-342M11rRhU/events/","game_center_url_mobile":"http://shl.se/gamecenter/qWX-342M11rRhU/events/","game_id":10372,"game_type":"Regular season game","game_uuid":"qWX-342M11rRhU","highlights_coverage_enabled":false,"home_team_code":"SAIK","home_team_result":0,"live_coverage_enabled":false,"overtime":false,"penalty_shots":false,"played":false,"season":"2019","series":"SHL","start_date_time":"2019-09-14T15:15:00+0200","ticket_url":"http://saik.ebiljett.nu/Home/tickets/438/False?style=shl","tv_channels":[],"venue":"Skellefteå Kraft Arena"},{"away_team_code":"BIF","away_team_result":0,"game_center_active":true,"game_center_url_desktop":"http://shl.se/gamecenter/qWX-342LGssIY/events/","game_center_url_mobile":"http://shl.se/gamecenter/qWX-342LGssIY/events/","game_id":10369,"game_type":"Regular season game","game_uuid":"qWX-342LGssIY","highlights_coverage_enabled":false,"home_team_code":"FHC","home_team_result":0,"live_coverage_enabled":false,"overtime":false,"penalty_shots":false,"played":false,"season":"2019","series":"SHL","start_date_time":"2019-09-14T15:15:00+0200","ticket_url":"https://www.ticketmaster.se/artist/frolunda-indians-biljetter/94573","tv_channels":[],"venue":"Scandinavium"}]
1|MagicMirror  | 2:55:50 PM MMM-SHL: Number of games: 364
1|MagicMirror  | 2:55:50 PM MMM-SHL: Getting standings
1|MagicMirror  | 2:55:51 PM MMM-SHL: Standings retrived: []
1|MagicMirror  | 2:55:51 PM MMM-SHL: Number of teams: 0
1|MagicMirror  | 2:55:51 PM MMM-SHL: []
1|MagicMirror  | 2:55:51 PM MMM-SHL: []
1|MagicMirror  | 2:55:51 PM MMM-SHL: Sceduled refresh at: Sat Sep 14 2019 18:00:00 GMT+0200 (CEST)

**Comment by anderswallerius** [comment] 2019-09-16 06:44
I'm having similar issue. I didn't get any info with "teams:" config commented out. I was assuming that it was because the series hadn't started. But same today. 
But for me it works with the "teams:" filtering.
Added all 12 teams from last year and I get an almost complete table. But I can't get Leksand and Oskarshamn to show up in table (tried filter 'LIF' and 'IKO' by chance).

**Comment by uFreke** [comment] 2019-09-22 00:23
After some tweaking I got it working. You need to modify node_helper.js file and replace the cases for Mora and Timrå with Leksand and Oskarshamn. Tried to just add them but didnt work. You need to replace it. Work with and without filtering of teams. I copied my code below.

```
            case "IKO":
                return {
                    icon: "https://www.shl.se/team_graphics/nef_shl/iko1-iko-891ab/special/30.png",
                    name: "Oskarshamn"
                };
            case "LIF":
                return {
                    icon: "https://www.shl.se/team_graphics/nef_shl/lif1-lif-57923/special/30.png",
                    name: "Leksand"
                };
```

**Comment by anderswallerius** [comment] 2019-09-22 10:29
Thanks! I'll try this later.
Edit: Made the changes to node_helper.js and it works perfect for me also, Thanks!!

**Comment by anderswallerius** [comment] 2019-09-28 08:56
uFreke>>Does your table update as it should? Seems like mine only load when I start MM.
I might be missing something here...

**Comment by uFreke** [comment] 2019-09-29 09:27
Yea, I have noticed the same thing. Will see if i can find something, I don't have very high coding skills but we'll see. For now I just do a pm2 restart each night at 3 am.

**Comment by bureus** [comment] 2019-09-30 17:35
Sorry for late reply @uFreke @anderswallerius @htilly, this has been fixed now! So please download the latest version! 

Update
Run git pull inside ../modules/MMM-SHL/ folder.
Run npm install inside ../modules/MMM-SHL/ folder

**Comment by bureus** [comment] 2019-09-30 20:18
I have also added the possibility to see time stamp of when the last updated happened. See read me, so you can ensure it gets updated :)

**Comment by htilly** [comment] 2019-09-30 20:55
Works great! Thanks for the fix!!

ps. Since we're probably most Swedish users for the module, maybe change the date format to yyyy/mm/dd ? (for the update timestamp) :)

**Comment by anderswallerius** [comment] 2019-10-01 05:11
Thanks for the fix bureus! 
htilly > Have you changed the local setting in the config file (almost at the top of default config file)?
On my MM the updated date format is Swedish std.

**Comment by anderswallerius** [comment] 2019-10-02 05:33
My table haven't updated after last nights games. Updated 2019-10-01 07:05:49 (yesterday when I updated the module and restarted MM).
Have I done something wrong/missing something?
My config only have clientId and secret.
Does the new version work for anyone?

**Comment by bureus** [comment] 2019-10-05 09:20
@anderswallerius I have similar problems actually, with updates. So will look into this today to ensure updates of the table. So what i am doing today is to calculate when the next game will end, and then update after that game has ended. Seems like it could be something with either timer or with conversion between date and time that is causing this. So will add a small db to the app, that will hold next update time and try with that approach instead of setting a timer based on ms which are like 2 days away.

**Closed as completed** 2019-10-05 14:17 UTC

**Comment by bureus** [comment] 2019-10-05 14:18
@anderswallerius i found a bug in the code, that was caused by 403 unauthorized refresh token flow. Which was causing update to fail. It has been resolved now in the latest release, so please verify if updates works now :)

**Comment by anderswallerius** [comment] 2019-10-07 05:20
@bureus I have now updated my SHL module, I guessing it will work now.
I saw in my logs that there were something with the token (but I don't understand these things well).
Thanks anyway!
